#!/bin/sh

info() { echo "\033[1;32m$1\033[0m"; }
title() { echo "\033[1;34m$1\033[0m"; }
warn() { echo "\033[1;31m$1\033[0m"; }

FILTER="*-${1:-"*"}"

pin() {
	local pin=""
	if [ ! -f $BASE_DIR/pins ]; then
		warn "$BASE_DIR/pins missing"
		return 1
	fi

	p=$(grep "$1" $BASE_DIR/pins | cut -d ' ' -f 2)

	if [ -z "$p" ]; then
		return 1
	fi

	echo $p
	return 0
}

dependencies() {
	local deps=""
	title "Fetching dependencies"
	for s in install.d/$FILTER; do
		. $s
		for r in $(depends); do
			deps="$deps $r"
		done;
	done

	deps=$(echo $deps | tr " " "\n" | sort | uniq | xargs)

	if [ -z "$deps" ]; then
		info "No dependencies found..."
	else
		info "Collected: '$deps', installing..."
		brew install $deps || brew upgrade $deps
	fi
}

# install core utils
brew install coreutils findutils --with-default-names

# DIRECTORIES
BASE_DIR=$(greadlink -f $(dirname $0))
REPOS_DIR=$BASE_DIR/git
VIM_BUNDLE_DIR=$BASE_DIR/dotfiles/.vim/bundle


cd $BASE_DIR

[ -z "$(find -wholename "./install.d/$FILTER")" ] && echo "nothing to install or $1 not found" && exit 0
[ ! -d ~/bin ] && mkdir ~/bin
[ ! -d $REPOS_DIR ] && mkdir $REPOS_DIR
[ ! -d $VIM_BUNDLE_DIR ] && mkdir $VIM_BUNDLE_DIR

for i in $BASE_DIR/bin/*; do
	ln -sf $i ~/bin/$(basename $i)
done



dependencies
title "Installing"
for s in install.d/$FILTER; do
	info "$s::install()"
	. $s
	install
	cd $BASE_DIR
done
