#!/bin/sh

depends() {
	echo "ack coreutils findutils bash-completion"
}

install() {
	# link to bash_profile
	ln -sf $BASE_DIR/dotfiles/.bashrc ~/.bash_profile
	ln -sf $BASE_DIR/dotfiles/.gitconfig ~/.gitconfig
}
